name = "kimlikdao-test-runner"
main = "runner.js"
route = { pattern = "test-runner.kimlikdao.org", custom_domain = true }

compatibility_date = "2023-01-01"
workers_dev = false
usage_model = "unbound"
no_bundle = true
minify = false
send_metrics = false
node_compat = false
