name: All benchmarks

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  benchmark:
    name: Micro benches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run crypto benchmarks
        run: |
          yarn
          make crypto.benchmark
