name: All benchmarks

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  benchmark_bun:
    name: Micro benches with bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Run crypto benchmarks
        run: |
          bun i
          make bench.bun

  benchmark_node:
    name: Micro benches with node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
      - name: Run crypto benchmarks
        run: |
          bun i
          make bench.node
