name: All tests

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  check_bun_tests:
    name: Unit tests with bun
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Run bun tests
        run: |
          bun i
          bun test
        id: test

  check_compiled_bun:
    name: Compiled tests with bun
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Google Closure Compiled tests with bun
        run: |
          bun i
          make test.bun  

  check_compiled_node:
    name: Compiled tests with node
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
      - name: Run Google Closure Compiled tests
        run: |
          bun i
          make test.node
